In [1]:
import pandas as pd

In [3]:

import os

print(os.getcwd())
print(os.listdir())

C:\Users\vriya
['.anaconda', '.anaconda-desktop', '.android', '.conda', '.copilot', '.dbus-keyrings', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.mamba', '.python_history', '.vscode', '.vscode-shared', 'adb', 'anaconda3', 'AppData', 'Application Data', 'churn_analysis.ipynb', 'Contacts', 'Cookies', 'customer_churn(3).db', 'customer_churn.db', 'customer_shopping_behaviour_analysis.ipynb', 'Desktop', 'Documents', 'Downloads', 'Favorites', 'Links', 'Local Settings', 'Microsoft', 'Module 2-20260529T101920Z-3-001.zip', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{0e7335df-6deb-11f0-b00d-50bbb5571427}.TM.blf', 'NTUSER.DAT{0e7335df-6deb-11f0-b00d-50bbb5571427}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{0e7335df-6deb-11f0-b00d-50bbb5571427}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'Pictures', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Videos', 'WPS Cloud', 'WPS Cloud Files']

In [4]:

import os

print(os.listdir(r"C:\Users\vriya\Desktop"))

['123.png', '2C00145  B.COM (SEM.-V)(CBCS).pdf', 'asiignment.xlsx', 'big bam boo baah.png', 'CapCut.lnk', 'CERTIFICATE', 'customer_shopping_analysis', 'Dear Hiring Manager.pdf', 'desktop.ini', 'Desktop.lnk', 'Downloads - Shortcut.lnk', 'Free Fire MAX Lost Treasure.lnk', 'JioHotstar - Watch TV Shows, Movies, Specials, Live Cricket & Football.lnk', 'MINE', 'Module 2-20260529T101920Z-3-001.zip', 'MovieBox - Watch Movies Free Online, Watch TV Series Online (Riya).lnk', 'PDF X.lnk', 'Personal - Edge.lnk', 'pf.png', 'pgAdmin 4.lnk', 'resume.jpeg', 'Richa 123', 'Riya - Chrome.lnk', 'Screenshots', 'Snowflake Schema-20260604T145628Z-3-001', 'SSC_KRISHNA.pdf', 'Star Schema-20260604T145628Z-3-001', 'Telegram.lnk', 'This PC - Shortcut.lnk', 'Untitled.png', 'Visual Studio Code.lnk', 'WhatsApp.lnk', 'WIN_20260909_14_55_32_Pro.zip', 'Year 2014.xlsx', 'Year 2016.xlsx', 'YouTube.lnk']

In [5]:

import os

folder = r"C:\Users\vriya\Desktop\customer_shopping_analysis"

print(os.listdir(folder))

['.ipynb_checkpoints', 'customer_shopping_behavior.csv', 'customer_shopping_behaviour_analysis.ipynb', 'Module 5']

In [6]:

import pandas as pd

df = pd.read_csv(
    r"C:\Users\vriya\Desktop\customer_shopping_analysis\customer_shopping_behavior.csv"
)

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [9]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [10]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [11]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [12]:
df.columns= df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [13]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [14]:
df= df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [15]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

# create a column age_group

In [16]:
labels = ['Young Adult', 'Adult', 'Middle_Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [17]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle_Aged
1   19  Young Adult
2   50  Middle_Aged
3   21  Young Adult
4   45  Middle_Aged
5   46  Middle_Aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle_Aged

# create column purchase frequency days

In [18]:
frequency_mapping={
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly' : 14,
    'Annually': 365,
    'Every 3 Month': 90}

df['purchase_frequency_days']= df['frequency_of_purchases'].map(frequency_mapping)

In [19]:
df[['purchase_frequency_days','frequency_of_purchases']].head(20)

    purchase_frequency_days frequency_of_purchases
0                      14.0            Fortnightly
1                      14.0            Fortnightly
2                       7.0                 Weekly
3                       7.0                 Weekly
4                     365.0               Annually
5                       7.0                 Weekly
6                      90.0              Quarterly
7                       7.0                 Weekly
8                     365.0               Annually
9                      90.0              Quarterly
10                     14.0              Bi-Weekly
11                     14.0            Fortnightly
12                     14.0            Fortnightly
13                      7.0                 Weekly
14                      7.0                 Weekly
15                     30.0                Monthly
16                     14.0              Bi-Weekly
17                     90.0              Quarterly
18                      7.0                 Weekly
19                     14.0              Bi-Weekly

In [20]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [21]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [22]:
df=df.drop('promo_code_used',axis=1)

In [23]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [25]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in .\AppData\Roaming\Python\Python314\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in .\AppData\Roaming\Python\Python314\site-packages (2.1.3)
Requirement already satisfied: typing-extensions>=4.6.0 in .\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [27]:
 pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in .\AppData\Roaming\Python\Python314\site-packages (26.2)
Collecting pip
  Downloading pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Downloading pip-26.2.1-py3-none-any.whl (1.8 MB)
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------------------- ---------------- 1.0/1.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 3.2 MB/s  0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 26.2
    Uninstalling pip-26.2:
      Successfully uninstalled pip-26.2
Successfully installed pip-26.2.1
Note: you may need to restart the kernel to use updated packages.

  WARNING: The scripts pip.exe, pip3.14.exe and pip3.exe are installed in 'C:\Users\vriya\AppData\Roaming\Python\Python314\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [28]:
import sqlalchemy, psycopg2
print(sqlalchemy.__version__, psycopg2.__version__)

2.1.3 2.9.13 (dt dec pq3 ext lo64)

In [29]:
from sqlalchemy import create_engine
# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"          # default user
password = "tiger"          # the password you set during installation
host = "localhost"             # if running locally
port = "5432"                  # default PostgreSQL port
database = "customer_behaviour" # the database you created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

# Step 2: Load DataFrame into PostgreSQL
table_name = "customer"        # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behaviour'.